"""
"""
DEVICE = "cuda:0"
SEED = 2
N_EPISODES = 1000
BATCH_SIZE = 128
BUFFER_SIZE = int(1e6)
GAMMA = 0.99
TAU = 0.001
LR = 0.0001
SAVE_DIRECTORY = "./pretrained_model"
UNITY_ENVIRONMENT_PATH = './reacher/Reacher.exe'
UNITY_NO_GRAPHIC = True
UNITY_WORKER_ID = 1